
FROM node:16-alpine AS builder
WORKDIR /app
COPY ./backend/package*.json ./
RUN npm install
COPY ./backend .
RUN npm run build

FROM node:16-alpine AS server
WORKDIR /app
COPY ./backend/package*.json ./
RUN npm install --production
COPY --from=builder ./app/public ./public
COPY --from=builder ./app/dist ./dist
EXPOSE 3001
CMD ["node", "./dist/index.js"]